### PR TITLE
feat: Support self hosted instances

### LINKED ISSUE #2: Feature request: Make it usable for self hosted instances
Kindly asking you to make it possible to use any cal.com instance by adding just the full URL in the shortcode.

### PR DESCRIPTION
**Pull request by CodeShakingSheep**
Adds support for self-hosted instances. Fix https://github.com/calcom/wp-plugin/issues/2 . Supports `https` and `http` instances.

Shortcode can be used like this:

Inline Embed:
```
[cal url=http(s)://custom-cal-com-domain.tld/username/meetingid]
```
To make inline embed work I also used the code from @mario-neuhold in PR https://github.com/calcom/wp-plugin/pull/4 . Thanks for the fix.

Popup:
```
[cal url=http(s)://custom-cal-com-domain.tld/username/meetingid type=2 text="Let's Talk!"]
```

### CODE REVIEW

**Comment by CodeShakingSheep** [comment]
@PeerRich @thatshycoder Who can merge this and publish a new version of the WP plugin? Thanks and happy Christmas holidays 🎄

**Comment by PeerRich** [comment]
@CodeShakingSheep can you fix the merge conflict? 🙏

**Comment by PeerRich** [comment]
also, how do i publish a new version? have never done this before

**Review by PeerRich — APPROVED** [review]

**Comment by CodeShakingSheep** [comment]
Hi @PeerRich ,
Thanks for picking this up.  :raised_hands: Tbh, I don't know either how to publish a new version. Have just done WP development so far, no plugin publishing. But I can do some research about it in the next days.

Edit: This is what's needed: https://kinsta.com/blog/publish-plugin-wordpress-plugin-directory/#publish-a-new-release So, I hope you still have access to the SVN repo :smile:  https://plugins.trac.wordpress.org/browser/cal-com/
Let me know if I can support any further with publishing a new release.

**Pull request merged**
